### ISSUE TITLE
Web form to file reports easily

### ISSUE THREAD

**Issue by stvnrlly** [18F/code-of-conduct#12]
Recognizing that there may be formal process requirements that make it difficult, it would be nice to see the reporting system be as easy as possible. The current informal process says:

> if you are being harassed in an 18F space, please speak to the organizer/admin of that space. If you can't reach them or are uncomfortable talking to them, any member of the 18F team can put you in touch with 18F Acting Executive Director Aaron Snow or Deputy Executive Director Hillary Hartley. GSA employees also have the option of raising their concerns with the Office of Human Resources Management or the Office of Civil Rights.

These are a lot of options, and require a fair amount of decisionmaking and effort on the part of the reporter. Additionally, they require a reporter to reveal him or herself--both by speaking with a representative of 18F and, at events, by publicly approaching that person--in order to make the report. It's possible that this has a chilling effect on making reports.

One possible alternative is to create a page on the 18F site with a form for submitting code of conduct reports. That form can send the report by email to the appropriate people, post in an appropriate Slack channel, or whatever else you want. Ideally, this form would have optional name and contact fields, so that reporters can choose to submit anonymously where privacy or retaliation is a concern. To make things easier for 18F, that page could also include some text about what information is useful as part of a report. It should also be clear where the report will go once submitted.

**Comment by jackiekazil** [comment]
@stvnrlly I really like this idea. 
Question -- have you seen anything like this before? Do you know of any examples that exist in the wild?

**Comment by stvnrlly** [comment]
Yes, I made a basic version of it for Code for DC: http://codefordc.org/contact.html. Since we don't have a high volume of incoming messages, we just use the main contact form for everything.

The form gets posted to a private group on Slack using [attachments](https://api.slack.com/docs/attachments) for formatting. In order to avoid having our API token in the clear, there's a tiny bit of Node running on Heroku that accepts the request, does the formatting, and sends a new request to Slack.

**Comment by hollyallen** [comment]
I believe this ticket is now defunct given the new formal guidance for reporting violations.

**Comment by stvnrlly** [comment]
I think so. The original post discusses anonymous reports as well, which is still something that may be worth addressing. A web form for that may not be feasible, but a bit of guidance on alternative ways to raise an issue may still be useful.
