### ISSUE TITLE
Replace 'Under Review' statement with revised, vetted Code of Conduct

### ISSUE THREAD

**Issue by jeanninehunter** [18F/code-of-conduct#28]
Replace the ["Under Review" statement](https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md) on [18F website](https://18f.gsa.gov/code-of-conduct/) with revised and vetted Code of Conduct.

**Comment by jeanninehunter** [comment]
[Pull requests](https://github.com/18F/code-of-conduct/pull/29) under review

**Comment by annalee** [comment]
And merged: https://github.com/18F/code-of-conduct/pull/29
